import type { Metadata } from "next";
import Provider from "./providers";
import "./globals.css"
import { Cormorant_Garamond, DM_Sans } from 'next/font/google'
import AuthGuard from "./AuthGuard";


export const metadata: Metadata = {
  title: "Cantarella (Revamped)",
  description: "Generated by create next app",
};

const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  style: ['normal', 'italic'],
  variable: '--font-display'
})

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-body'
})

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${cormorant.variable} ${dmSans.variable} antialiased`}
      >
        <Provider>
          <AuthGuard>
            {children}
          </AuthGuard>
        </Provider>
      </body>
    </html>
  );
}
